version: '3'
services:
  backend:
    container_name: 'file_share_chat'
    build: .
    depends_on:
      - mongo_database
    ports:
      - 5000:5000
    command: yarn start

  mongo_database:
    image: mongo
    restart: always
    container_name: 'file_share_chat_mongo'
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017

  redis_cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes: 
      - cache:/data

volumes:
  mongodb_data_container:
  cache: