version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
     - .:/app
     - /app/node_modules
    command: yarn start:dev
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    env_file:
      .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
  
  